<?php

/**
 * @file
 * Main module file for Classy Paragraphs.
 */

// Paragraphs entity bundle.
define('CLASSY_PARAGRAPHS_ENTITY_TYPE', 'paragraphs_item');
// Full content view mode machine name.
define('CLASSY_PARAGRAPHS_VIEW_MODE', 'full');
// Field type classy paragraphs list.
define('CLASSY_PARAGRAPHS_FIELD_TYPE_LIST', 'cp_list');

// Include fields.
require_once dirname(__FILE__) . '/includes/classy_paragraphs.fields.inc';

/**
 * Get list of options from other modules.
 *
 * @param $field
 * @param $instance
 * @return array
 */
function classy_paragraphs_get_options($field, $instance) {
  $options = array();
  $options = module_invoke_all('classy_paragraphs_list_options', $options, $field, $instance);
  backdrop_alter('classy_paragraphs_list_options', $options, $field, $instance);
  return $options;
}

/**
 * Implements template_preprocess_paragraphs_item()
 */
function classy_paragraphs_preprocess_paragraphs_item(&$variables, $hook) {
  if ($hook == CLASSY_PARAGRAPHS_ENTITY_TYPE) {
    $paragraphs_item_entity = $variables['paragraphs_item'];
    $classes = classy_paragraphs_get_classes($paragraphs_item_entity);
    foreach ($classes as $class) {
      $variables['classes_array'][] = backdrop_html_class($class);
    }
  }
}

/**
 * Get class names from paragraph item.
 *
 * @param ParagraphsItemEntity $item
 *
 * @return string[]
 */
function classy_paragraphs_get_classes(ParagraphsItemEntity $item) {
  $classes = array();
  $instances = field_info_instances(CLASSY_PARAGRAPHS_ENTITY_TYPE, $item->bundle);

  foreach ($instances as $instance) {
    $field_name = $instance['field_name'];
    $field = field_info_field($field_name);

    if ($field['type'] == CLASSY_PARAGRAPHS_FIELD_TYPE_LIST) {
      // Determine the list of languages to iterate on.
      $languages = field_available_languages(CLASSY_PARAGRAPHS_ENTITY_TYPE, $field);

      foreach ($languages as $langcode) {
        if (!empty($item->{$field_name}[$langcode])) {
          foreach ($item->{$field_name}[$langcode] as $field_item) {
            // Separate out classes saved with spaces.
            // This happens if the set name is saved with the class name.
            $values = explode(' ', $field_item['value']);
            foreach ($values as $value) {
              $classes[] = $value;
            }
          }
        }
      }
    }
  }

  return array_unique($classes);
}
