<?php

/**
 * @file
 * classy_paragraphs_ui.install
 */

/**
 * Move Classy Paragraph UI settings from variables to config.
 */
function classy_paragraphs_ui_update_1000() {
  // Migrate variables to config.
  $config = config('classy_paragraphs_ui.settings');
  $config->set('classy_paragraphs_settings', update_variable_get('classy_paragraphs_settings', ''));
  $config->save();

  // Delete variables.
  update_variable_del('classy_paragraphs_settings');
}

/**
 * Clean up config structure and extend to work with sets.
 */
function classy_paragraphs_ui_update_1100() {
  $old_config = config('classy_paragraphs_ui.settings');
  $config = config('classy_paragraphs_ui.classes');
  foreach($old_config->get('classy_paragraphs_settings') as $oldclass) {
    $class = array(
      'name' => $oldclass['css_class_name'],
      'label' => $oldclass['css_class_display'],
      'sets' => array(),
    );
    $config->set($oldclass['css_class_name'], $class);
  }
  $config->save();
  $old_config->clear('classy_paragraphs_settings');
  $old_config->save();
}

/**
 * Add a weight column to each class per set.
 */
function classy_paragraphs_ui_update_1101() {
  $config = config('classy_paragraphs_ui.classes');
  $config_instances = config('classy_paragraphs_ui.class_instances');

  $classes = $config->getData();

  foreach ($classes as $class_name => $class) {
    foreach ($class['sets'] as $set) {
      $class_instance = $config_instances->get($set . '.' . $class_name);
      if ($class_instance == NULL) {
        $config_instances->set($set . '.' . $class_name, array('weight' => 0));
      }
    }
  }
  $config_instances->save();
}
